archetypeDir           = "archetypes"
author                 = "DiBotak"
baseUrl                = "http://localhost:1313"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
theme                  = "hugo-theme-pixyll"
title                  = "DiBotak"
enableEmoji            = true
DefaultContentLanguage = "en"
#disqusShortname        = ""

[Languages]
[Languages.en]
weight = 1

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post"]
  #google_analytics_id = ""
  twitter_username = "dibfaqih"
  paginate = 5
